version: '3.8'

services:
  # Contenedor todo-en-uno
  stack-completo:
    build: .
    container_name: python_ml_stack
    ports:
      - "8888:8888"  # JupyterLab UI
      - "8080:8080"  # Spark Master UI
      - "5000:5000"  # MLflow UI
    volumes:
      - ./notebooks:/app/notebooks
      - mlflow-artifacts:/app/mlflow_artifacts
    networks:
      - ml-net
    depends_on:
      - postgres-db

  # Base de datos para MLflow
  postgres-db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_pass
      - POSTGRES_DB=mlflow_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ml-net

volumes:
  postgres-data:
  mlflow-artifacts:

networks:
  ml-net:
    driver: bridge
